name: Scanner docker image med Trivy
description: Skanner docker image med Trivy og laster opp resultatet til GitHub Security

inputs:
  image:
    description: Docker image som skal skannes
    required: true
  severity:
    description: Minimum severity for sårbarheter som skal vises i GitHub Security
    required: false
    default: MEDIUM,HIGH,CRITICAL # Prøver å filtrere bort lave og uklassifiserte sårbarheter
  ignore-unfixed:
    description: Ignorer sårbarheter som ikke er fikset
    required: false
    default: 'false' # Vi vil se alle sårbarheter, også de som ikke er fikset
  team:
    description: Team som eier applikasjonen
    required: true
    default: pia
  project_id:
    description: Google Cloud project ID
    required: true
  identity_provider:
    description: Workload Identity Provider
    required: true
  upload-artifact:
    description: Last opp Trivy sin rårapport som artifact
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: nais/login@v0
      with:
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        team: ${{ inputs.team }}

    - name: Run Trivy vulnerability scanner on docker image
      uses: aquasecurity/trivy-action@master
      env:
        TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
      with:
        image-ref: ${{ inputs.image }}
        ignore-unfixed: ${{ inputs.ignore-unfixed }}
        vuln-type: os,library
        limit-severities-for-sarif: true
        severity: ${{ inputs.severity }}
        format: sarif
        output: trivy-results.sarif # Filen som genereres av trivy brukes i de neste stegene

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: trivy-results.sarif

    - name: Laster opp Trivy sin rårapport som artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: trivy-results
        path: trivy-results.sarif