name: Scanner docker image med Trivy
description: Skanner docker image med Trivy og laster opp resultatet til GitHub Security

inputs:
  image:
    description: Docker image som skal skannes
    required: true
  team:
    description: Team som eier applikasjonen
    required: true
    default: pia

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: nais/login@v0
      with:
        project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
        identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        team: ${{ inputs.team }}
    - run: docker pull ${{ inputs.image }}
      shell: bash
    - name: Run Trivy vulnerability scanner on docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.image }}
        ignore-unfixed: false # Vi vil se alle sårbarheter, også de som ikke er fikset
        vuln-type: os,library
        limit-severities-for-sarif: true
        severity: MEDIUM,HIGH,CRITICAL # Prøver å filtrere bort lave og uklassifiserte sårbarheter
        format: sarif
        output: trivy-results.sarif # Filen som genereres av trivy brukes i de neste stegene
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: trivy-results.sarif
    - name: Laster opp Trivy sin rårapport som artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-results
        path: trivy-results.sarif