name: Scanner docker image med Trivy
description: Skanner docker image med Trivy og laster opp resultatet til GitHub Security

inputs:
  image:
    description: Docker image som skal skannes
    required: true
  severity:
    description: Minimum severity for sårbarheter som skal vises i GitHub Security
    required: false
    default: MEDIUM,HIGH,CRITICAL # Prøver å filtrere bort lave og uklassifiserte sårbarheter
  ignore-unfixed:
    description: Ignorer sårbarheter som ikke er fikset
    required: false
    default: 'false' # Vi vil se alle sårbarheter, også de som ikke er fikset
  team:
    description: Team som eier applikasjonen
    required: true
    default: pia
  upload-artifact:
    description: Last opp Trivy sin rårapport som artifact
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf # v0
      with:
        team: ${{ inputs.team }}

    - name: Run Trivy vulnerability scanner on docker image
      uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
      env:
        TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db:1"
        TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
      with:
        image-ref: ${{ inputs.image }}
        ignore-unfixed: ${{ inputs.ignore-unfixed }}
        vuln-type: os,library
        limit-severities-for-sarif: true
        severity: ${{ inputs.severity }}
        format: sarif
        output: trivy-results.sarif # Filen som genereres av trivy brukes i de neste stegene

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@99df26d4f13ea111d4ec1a7dddef6063f76b97e9 # v4.37.0
      if: always()
      with:
        sarif_file: trivy-results.sarif

    - name: Laster opp Trivy sin rårapport som artifact
      if: ${{ inputs.upload-artifact == 'true' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: trivy-results
        path: trivy-results.sarif
