name: "forebyggingsplan e2e-test"
description: "Kjører en full ende-til-ende test av hele forebyggingsplan-stacken"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: "navikt/forebyggingsplan-frontend"
    - uses: actions/setup-node@v3
      name: Setup node
      with:
        node-version: "16"
    - run: npm run e2e
      shell: bash
      name: Start e2e tests
